package net.darmo_creations.mccode.interpreter;

/**
 * A stack trace element generated by {@link Scope} objects.
 */
public class StackTraceElement {
  private final String scopeName;

  /**
   * Create a stack trace element.
   *
   * @param scopeName Name of the scope it represents.
   */
  public StackTraceElement(final String scopeName) {
    this.scopeName = scopeName;
  }

  /**
   * Return associated scope’s name.
   */
  public String getScopeName() {
    return this.scopeName;
  }
}
